name: Add Task ID to Pull Request Title
on:
  pull_request:
    types:
      - opened

jobs:
  add-task-id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract task ID
        id: extract-task-id
        run: |
          branch_name=$(git symbolic-ref --short HEAD)
          IFS="/" read -ra branch_parts <<< "$branch_name"
          if [[ ${#branch_parts[@]} -ge 2 && ${branch_parts[1]} =~ ^T\d+-\d+$ ]]; then
            task_id=${branch_parts[1]}
          else
            task_id=""
          fi
          echo "::set-output name=task_id::$task_id"

      - name: Update Pull Request title
        if: steps.extract-task-id.outputs.task_id != ''
        uses: actions/github-script@v4
        with:
          script: |
            const taskID = '${{ steps.extract-task-id.outputs.task_id }}';
            const prTitle = github.context.payload.pull_request.title;
            github.issues.update({
              issue_number: context.issue.number,
              title: `[${taskID}] ${prTitle}`
            });