name: Build and Test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: "https://eenvlywmoqrtxjqkjgfp.supabase.co"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlbnZseXdtb3FydHhqcWtqZ2ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzk2OTQyMjEsImV4cCI6MTk5NTI3MDIyMX0.w5pZqwK08xNB23Xd6iGJ1YvGAh4BAYzEXNKojyrsxfI"
      SUPABASE_JWT_SECRET: "fgv1x07XZ1d22I6Zu2fMIFoD7JigC1W4SOq51Gn/zwWVxASUU+KRrXbwYPtgD/zpRYVmHqi1sMj5EuYLpnPnFQ=="
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build

  merge-approval:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Check if build succeeded
        run: |
          if [ -d ".next" ]; then
            echo "Build succeeded! Branch can be merged."
          else
            echo "Build failed! Please fix the build errors before merging."
            exit 1
          fi
